FROM python:3.10-slim

ENV ROOT_DIR=/usr/app

WORKDIR $ROOT_DIR

RUN apt-get update \
&& apt-get install -y gcc \
&& rm -rf /var/lib/apt/lists/* \
&& apt-get clean

ENV PIPENV_VENV_IN_PROJECT=1
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

RUN pip install --no-cache-dir pipenv

COPY search_service/Pipfile Pipfile
COPY search_service/Pipfile.lock Pipfile.lock
RUN pipenv install --deploy --ignore-pipfile

COPY common/ common/
COPY search_service/ search_service/

ENV PYTHONPATH=$ROOT_DIR

CMD ["pipenv", "run", "uvicorn", "search_service.app.main:app", "--host", "0.0.0.0", "--port", "8000"]
